import pandas as pd
import smtplib, ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

#Configuration Information

datapath = 'E:\\Satish\\PerformanceTracker\\data\\'

#Data Load
resourcelist = pd.read_csv(datapath + 'ResourceListTest1.csv')

def final_result(resourcelist):
    for i in resourcelist.index:
        if resourcelist['Active'][i] == 1:
            rname = resourcelist['ResourceName'][i]
            rnamearray = rname.split(' ')
            lname = resourcelist['LeadName'][i]
            lnamearray = lname.split(' ')
            mname = resourcelist['ManagerName'][i]

            to = resourcelist['ResourceEmail'][i]
            frm = 'DONOTREPLY_performance.report@travelex.com'
            msg = MIMEMultipart('alternative')
            msg['Subject'] = "Mirror Image"
            msg['From'] = frm
            msg['To'] = resourcelist['ResourceEmail'][i]
            msg['Cc'] = resourcelist['LeadEmail'][i]
            msg['Bcc'] = resourcelist['ManagerEmail'][i]
            cc = resourcelist['LeadEmail'][i]
            bcc = resourcelist['ManagerEmail'][i]

            html_string = '''
                                <html>
                                  <head><title>Mirror Image</title></head>
                                  <link rel="stylesheet" type="text/css" href="df_style.css"/>
                                  <body>
                                    <table>
                                    <tr>Hi {toname},</tr>
                                    <tr></tr>
                                    <tr>Thank you for your tremendous efforts and contribution.</tr>
                                    <tr>Monthly KPI numbers are a mirror image of involvement and envisioned to assist in concentrating on improvement areas.</tr>
                                    <tr></tr>
                                    <tr>If you feel like lagging without any hesitation, reach out to {lead} , together we will work out the best possible alternative, </tr>
                                    <tr>and you can expedite and turn weakness to strength.</tr>
                                    <tr></tr>
                                    <tr>Have a look at your performance report below.</tr>
                                    <tr></tr>
                                    <tr></tr>
                                    <tr>Task Wise Count</tr>
                                    <tr>===================================================================================================</tr>
                                    </table>
                                                                    
                                    <table>                                
                                    <tr>---------------------------------------------------------------------------------------------------</tr>
                                    <tr></tr>
                                    <tr>Month Wise Score</tr>                                
                                    </table>
                                    
                                    <table>
                                    <tr>===================================================================================================</tr>
                                    <tr></tr>
                                    <tr>Thanks & Regards,</tr>
                                    <tr>{manager}</tr>
                                    <tr></tr><tr></tr><tr></tr>
                                    <tr>Please contact your team management with any questions or concerns about this mail.</tr>
                                    <tr>This email was automatically generated by Application Support Team.</tr>
                                    <tr></tr>
                                    </table>
                                  </body>
                                </html>.
                                '''
            html = html_string.format(toname=rnamearray[0], lead=lnamearray[0], manager=mname)
            part = MIMEText(html, 'html')
            msg.attach(part)

            # Open mail connection
            server = smtplib.SMTP('145.224.216.21', 25)
            server.connect('145.224.216.21')
            server.sendmail(frm, [to, cc, bcc], msg.as_string())
            server.quit()
            html_string = ''

def main():

    final_result(resourcelist)

if __name__ == "__main__":
    main()